# -*- coding: utf-8 -*-
"""backtest_engine.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PG11PGlhqBKrydUi-Way1x3uQq5WBrws
"""

import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt

# 1. Get the data
assets = ["^NSEI", "GC=F", "QQQ"]
data = yf.download(assets, start="2021-01-01", auto_adjust=True)['Close']
returns = data.pct_change().dropna()

# 2. Strategy: 40% India Stocks, 30% Gold, 30% US Tech
weights = np.array([0.4, 0.3, 0.3])
portfolio_returns = returns.dot(weights)

# 3. Calculate Portfolio Metrics
portfolio_growth = (portfolio_returns + 1).cumprod()
annual_return = portfolio_returns.mean() * 252
annual_vol = portfolio_returns.std() * np.sqrt(252)
sharpe_ratio = (annual_return - 0.05) / annual_vol

# 4. Calculate Benchmark (Nifty) Metrics
nifty_growth = (returns['^NSEI'] + 1).cumprod()
nifty_annual_ret = returns['^NSEI'].mean() * 252
nifty_annual_vol = returns['^NSEI'].std() * np.sqrt(252)
nifty_sharpe = (nifty_annual_ret - 0.05) / nifty_annual_vol

# 5. Print the Comparison Table
print(f"\n{'Metric':<20} | {'My Portfolio':<15} | {'Nifty 50':<15}")
print("-" * 55)
print(f"{'Total Return':<20} | {((portfolio_growth.iloc[-1]-1)*100):>13.1f}% | {((nifty_growth.iloc[-1]-1)*100):>13.1f}%")
print(f"{'Annualized Return':<20} | {annual_return:>14.2%} | {nifty_annual_ret:>14.2%}")
print(f"{'Annualized Risk':<20} | {annual_vol:>14.2%} | {nifty_annual_vol:>14.2%}")
print(f"{'Sharpe Ratio':<20} | {sharpe_ratio:>14.2f} | {nifty_sharpe:>14.2f}")

# 6. Make the Final Graph
plt.figure(figsize=(12,7))
plt.plot(nifty_growth, label='Nifty 50 (Benchmark)', color='red', linestyle='--')
plt.plot(portfolio_growth, label='My Quant Strategy', color='blue', linewidth=3)
plt.title('Final Backtest Results: Quant Strategy vs. Market Index')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()